version: '2'
services:
  # webserver
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
      - database
    volumes:
      - .:/code
  # database
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=imooc123456"
      - "MYSQL_DATABASE=movie_cat"
      - "MYSQL_USER=root"
    ports:
        - "33061:3306"
